source "https://rubygems.org"

gem "guard", "~> 2.18"
gem "guard-livereload", "~> 2.5"
gem "jekyll", "~> 4.3"
gem "jekyll-github-metadata", "~> 2.16"
gem "jekyll-polyglot", "~> 1.7"
gem "jekyll-seo-tag", "~> 2.8"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"
