source "https://rubygems.org"

gem "base64", "~> 0.3.0"
gem "csv", "~> 3.3"
gem "guard-livereload", "~> 2.5"
gem "guard", "~> 2.18"
gem "jekyll-polyglot", "~> 1.7"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll", "~> 4.3"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"
