# Resume Schema Definition
type: object
required:
  - name
  - title
  - job_title
  - contact
  - education
  - experience
  - projects
  - skills
  - certifications
  - languages
properties:
  name:
    type: string
  title:
    type: string
  job_title:
    type: string

  contact:
    type: object
    required:
      - data
    properties:
      data:
        type: array
        minItems: 1
        items:
          type: object
          required:
            - icon
            - text
            - link
          properties:
            icon:
              type: string
              pattern: ^fa-[a-zA-Z-]+$
            text:
              type: string
            link:
              type: string
              format: uri

  education:
    type: object
    required:
      - title
      - data
    properties:
      title:
        type: string
      data:
        type: array
        minItems: 1
        items:
          type: object
          required:
            - university
            - duration
            - location
            - major
          properties:
            university:
              type: string
            duration:
              type: string
              pattern: ^\d{4}\s*-\s*\d{4}$
            location:
              type: string
            major:
              type: string

  experience:
    type: object
    required:
      - title
      - data
    properties:
      title:
        type: string
      data:
        type: array
        minItems: 1
        items:
          type: object
          required:
            - title
            - duration
            - company
            - location
            - description
          properties:
            title:
              type: string
            duration:
              type: string
            company:
              type: string
            location:
              type: string
            link:
              type: string
              format: uri
            description:
              type: array
              items:
                type: string

  projects:
    type: object
    required:
      - title
      - data
    properties:
      title:
        type: string
      data:
        type: array
        items:
          type: object
          required:
            - name
            - description
            - contribution
          properties:
            name:
              type: string
            description:
              type: array
              items:
                type: string
            contribution:
              type: string

  skills:
    type: object
    required:
      - title
      - data
    properties:
      title:
        type: string
      data:
        type: array
        minItems: 1
        items:
          type: object
          required:
            - title
            - items
          properties:
            title:
              type: string
            items:
              type: array
              minItems: 1
              items:
                type: object
                required:
                  - name
                  - rate
                properties:
                  name:
                    type: string
                  rate:
                    type: integer
                    minimum: 1
                    maximum: 5

  certifications:
    type: object
    required:
      - title
      - link_text
      - data
    properties:
      title:
        type: string
      link_text:
        type: string
      data:
        type: array
        items:
          type: object
          required:
            - name
            - link
            - date
          properties:
            name:
              type: string
            link:
              type: string
              format: uri
            date:
              type: string

  languages:
    type: object
    required:
      - title
      - data
    properties:
      title:
        type: string
      data:
        type: array
        minItems: 1
        items:
          type: object
          required:
            - name
            - proficiency
          properties:
            name:
              type: string
            proficiency:
              type: string
